from . import profesor
from . import estudiante
from . import apoderado
from . import curso
from . import curso_materia
from . import apoderado
from . import materia
from . import evento
from . import archivo_evento
from . import bitacora_evento
from . import ejemplo
from . import aviso
from . import archivo_aviso
from . import bitacora_aviso
from . import objetivo_aviso
from . import asistencia_aviso
from . import nota
from . import boletin
from . import cuestionario
from . import pregunta_cuestionario
from . import respuesta_estudiante